name: formula1
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numpy
  - scipy
  - pandas
  - seaborn
  - python=3.9
  - beautifulsoup4
  - sqlalchemy
  - pymysql
  - jupyter
  - requests
  - selenium=4.2
  - webdriver-manager
  - geocoder
  - plotly=4.12.0
  - scikit-learn=1.1.2
  - python-kaleido
  - mlxtend
  - xgboost
  - tensorflow
  - tabulate
  - shap
  - pip 
  - pip:
      - fastf1==2.3.0
